#!/usr/bin/env bash
# Reconstruct every mesh in a folder of STL files.
#
#   agent/run_folder.sh <stl_dir> [options] [run_system.sh flags...]
#
#   --config <yaml>   base config (default: agent/configs/dialogue_lean.yaml).
#                     Model paths, environments and servers come from it; only the
#                     dataset, the run name and the limit are replaced.
#   --name <name>     run name (default: the folder name)
#   --limit <n>       only the first n parts (sorted by file name)
#   --out <dir>       after the run, copy each part's best.py / best.stl and a
#                     results.csv there (agent/tools/export_results.py)
#
# Any other flag goes to run_system.sh as is (--keep-servers, --no-servers, ...).
# Every `*.stl` directly in <stl_dir> is one part; subfolders are not read.
#
# The generated config is kept as work_dirs/configs/<name>.yaml, and the run
# directory is work_dirs/<name> (with a suffix if the name is taken).
set -euo pipefail

AGENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$AGENT_DIR")"

usage() { awk 'NR==1 {next} /^#/ {sub(/^# ?/, ""); print; next} {exit}' "${BASH_SOURCE[0]}"; }

[[ $# -ge 1 && "$1" != -h && "$1" != --help ]] || { usage; exit 2; }
STL_DIR="$1"; shift
BASE_CONFIG="$AGENT_DIR/configs/dialogue_lean.yaml"
NAME=""; LIMIT=""; OUT_DIR=""; PASS=()
while (( $# )); do
    case "$1" in
        --config) BASE_CONFIG="$2"; shift 2 ;;
        --name)   NAME="$2"; shift 2 ;;
        --limit)  LIMIT="$2"; shift 2 ;;
        --out)    OUT_DIR="$2"; shift 2 ;;
        *)        PASS+=("$1"); shift ;;
    esac
done

[[ -d "$STL_DIR" ]] || { echo "No such directory: $STL_DIR" >&2; exit 1; }
STL_DIR="$(cd "$STL_DIR" && pwd)"
compgen -G "$STL_DIR/*.stl" >/dev/null || { echo "No .stl files in $STL_DIR" >&2; exit 1; }
[[ -f "$BASE_CONFIG" ]] || { echo "No such config: $BASE_CONFIG" >&2; exit 1; }
NAME="${NAME:-$(basename "$STL_DIR")}"

PY="${CAD_AGENT_PYTHON:-python3}"
"$PY" -c 'import yaml' 2>/dev/null || {
    echo "$PY has no PyYAML; set CAD_AGENT_PYTHON to the run environment's python" >&2; exit 1; }

CONFIG="$REPO_ROOT/work_dirs/configs/$NAME.yaml"
mkdir -p "$(dirname "$CONFIG")"
"$PY" - "$BASE_CONFIG" "$CONFIG" "$STL_DIR" "$NAME" "$LIMIT" <<'PY'
import sys
import yaml

base, out, stl_dir, name, limit = sys.argv[1:]
with open(base, encoding="utf-8") as stream:
    config = yaml.safe_load(stream)
experiment = config.setdefault("experiment", {})
# The split is named after the run: part ids become `<name>/<file stem>`.
experiment["details"] = [{name: stl_dir}]
experiment.pop("subsample", None)
if limit:
    experiment["limit"] = int(limit)
else:
    experiment.pop("limit", None)
config.setdefault("launch", {})["run_name"] = name
with open(out, "w", encoding="utf-8") as stream:
    stream.write(f"# Generated by agent/run_folder.sh from {base}\n")
    yaml.safe_dump(config, stream, sort_keys=False, allow_unicode=True)
PY
echo "Config: $CONFIG"

LOG="$(mktemp)"
trap 'rm -f "$LOG"' EXIT
set +e
"$AGENT_DIR/run_system.sh" "$CONFIG" "${PASS[@]}" 2>&1 | tee "$LOG"
rc=${PIPESTATUS[0]}
set -e

if [[ -n "$OUT_DIR" ]]; then
    RUN_DIR="$(sed -n 's/^Run directory: *//p' "$LOG" | tail -1)"
    if [[ -n "$RUN_DIR" && -f "$RUN_DIR/per_figure.json" ]]; then
        "$PY" "$AGENT_DIR/tools/export_results.py" "$RUN_DIR" "$OUT_DIR"
    else
        echo "No finished run directory to export from (run exit code $rc)" >&2
        (( rc != 0 )) || rc=1
    fi
fi
exit "$rc"
